name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: 5.x

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.13

      - name: Build
        run: dotnet build src/MockLogging.sln -p:Version=${{ steps.gitversion.outputs.fullSemVer }}

      - name: Test
        run: dotnet test src/MockLogging.sln --no-build --verbosity normal

      - name: Pack
        run: dotnet pack src/MockLogging.sln -c Release -o package -p:Version=${{ steps.gitversion.outputs.fullSemVer }}

      - name: Publish
        run: dotnet nuget push package/*.nupkg -s 'https://api.nuget.org/v3/index.json' -k ${{secrets.NUGET_API_KEY}}
